CREATE TABLE "Users" (
	"Id" SERIAL PRIMARY KEY,
	"FirstName" VARCHAR(30) NOT NULL,
	"LastName" VARCHAR(30) NOT NULL,
	"Username" VARCHAR(50) NOT NULL UNIQUE,
	"Email" VARCHAR(128) NOT NULL UNIQUE,
	"Password" TEXT NOT NULL,
	"DocumentNumber" CHAR(11) NOT NULL,
	"Role" VARCHAR(5) NOT NULL,
	"CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" TIMESTAMP,
	"DeletedAt" TIMESTAMP
)
	
