version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4

  gamacoredb:
    image: postgres

  gama.api:
    image: ${DOCKER_REGISTRY-}gamaapi
    build:
      context: .
      dockerfile: src/services/GamaCore/Dockerfile

  nationalgeographicdb:
    image: postgis/postgis:15-3.3

  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
  pgadmin_data:
  postgres_data: