version: '3.4'

services:
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=garotosdeprograma.ec@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  gamacoredb:
    container_name: gamacoredb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=GamaCoreDb
      - TZ:'UTC'
      - PGTZ:'UTC'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

  nationalgeographicdb:
    container_name: nationalgeographicdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=NationalGeographicDb
      - TZ:'UTC'
      - PGTZ:'UTC'
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data/ 
  
  rabbitmq:
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  gama.api:
    container_name: gama.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:GamaCoreDbConnectionString=Host=gamacoredb;Port=5432;Database=GamaCoreDb;Username=admin;Password=admin1234;Pooling=true;"
    depends_on:
      - gamacoredb
    ports:
      - "8001:80"

networks:
  rabbitmq_go_net:
    driver: bridge